main: me.sabrewolf.skyservers.pixelmon.Main
name: AutoExp
author: _SaBrEWoLf, pvmac2194
website: http://dev.bukkit.org/bukkit-plugins/auto-exp/
version: 1.2
depend: [Essentials]
commands:
    autoexp:
        description: /autoexp <Command>
        aliases: [ae]
        usage: /autoexp
permissions:
  autoexp.reload:
    description: Allows the admin to reload the configuration.
  autoexp.setval:
    description: Allows the admin to set AutoExp's variables.
  autoexp.donor:
    description: Donator multiplier in config.yml
  autoexp.receiveExp:
    description: Allows the player to actually receive EXP. 